name 'luks'
maintainer 'GSI Helmholtzzentrum für Schwerionenforschung GmbH'
maintainer_email 'linuxgroup@gsi.de'
license 'GPL-3.0'
description 'Installs/Configures luks'
version '0.1.0'
chef_version '>= 12.5'

source_url 'https://git.gsi.de/chef/cookbooks/luks'
issues_url 'https://git.gsi.de/chef/cookbooks/luks/issues'
